apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: with-dead-letter-sink
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: with-dead-letter-sink
  schedule: "* * * * *"
  data: Hello World!
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: with-dead-letter-sink
spec:
  delivery:
    deadLetterSink:
      ref:
        apiVersion: eventing.knative.dev/v1
        kind: Broker
        name: dead-letter-sink-broker
    backoffDelay: PT1S
    backoffPolicy: linear
    retry: 5
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: dead-letter-sink-broker
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: my-service-trigger
spec:
  broker: with-dead-letter-sink
  subscriber:
    uri: http://fail.default.svc.cluster.local
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-display
spec:
  broker: dead-letter-sink-broker
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
---
apiVersion: v1
kind: Service
metadata:
  name: event-display
spec:
  selector:
    app: event-display
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: event-display
  labels:
    app: event-display
spec:
  containers:
    - name: event-display
      image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
      ports:
        - containerPort: 8080
