apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: event-transformation
spec:
  delivery:
    deadLetterSink:
      ref:
        apiVersion: eventing.knative.dev/v1
        kind: Broker
        name: dead-letter-sink-broker
    backoffDelay: PT1S
    backoffPolicy: linear
    retry: 5
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-transformation
spec:
  broker: event-transformation
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-transformation-function
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-transformation-function
spec:
  template:
    spec:
      containers:
        - image: quay.io/kevent-mesh/event-tranformation-function/event-tranformation-function
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-display
spec:
  broker: dead-letter-sink-broker
  filters:
    cesql: dataschema = 'https://my-org.com/schemas/orders/v2'
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
---
apiVersion: v1
kind: Service
metadata:
  name: event-display
spec:
  selector:
    app: event-display
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: event-display
  labels:
    app: event-display
spec:
  containers:
    - name: event-display
      image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
      ports:
        - containerPort: 8080
