apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: sequence
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  steps:
    - ref:
        apiVersion: v1
        kind: Service
        name: first
    - ref:
        apiVersion: v1
        kind: Service
        name: second
  reply:
    ref:
      kind: Service
      apiVersion: v1
      name: event-display


---
apiVersion: v1
kind: Service
metadata:
  name: event-display
spec:
  selector:
    app: event-display
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: event-display
  labels:
    app: event-display
spec:
  containers:
    - name: event-display
      image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
      ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: first
spec:
  selector:
    app: first
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: first
  labels:
    app: first
spec:
  containers:
  - env:
    - name: MESSAGE
      value: ' - Handled by first!'
    name: first-appender
    image: gcr.io/knative-releases/knative.dev/eventing/cmd/appender
    ports:
      - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: second
spec:
  selector:
    app: second
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: second
  labels:
    app: second
spec:
  containers:
  - env:
    - name: MESSAGE
      value: ' - Handled by second!'
    name: second-appender
    image: gcr.io/knative-releases/knative.dev/eventing/cmd/appender
    ports:
      - containerPort: 8080
